# Waveshare ESP32-S3 Touch LCD 5" (B) - 1024x600 / GT911 / CH422G
substitutions:
  name: "ws-esp32s3-5b"
  friendly_name: 'Panel 5" Waveshare'
  room: "Salon"
  project: "waveshare.esp32s3-5b"
  version: "1.0.0"

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  area: ${room}
  project:
    name: ${project}
    version: ${version}
  platformio_options:
    build_flags: "-DBOARD_HAS_PSRAM"
    board_build.arduino.memory_type: qio_opi
    board_build.flash_mode: dio
    board_upload.maximum_ram_size: 524288

esp32:
  board: esp32-s3-devkitc-1
  variant: ESP32S3
  flash_size: 8MB
  framework:
    type: esp-idf
    sdkconfig_options:
      COMPILER_OPTIMIZATION_SIZE: y
      CONFIG_ESP32S3_DATA_CACHE_64KB: "y"
      CONFIG_ESPTOOLPY_FLASHSIZE_8MB: "y"
      CONFIG_FREERTOS_HZ: "1000"
      CONFIG_ESP_DEFAULT_CPU_FREQ_MHZ_160: y
      CONFIG_ESP_DEFAULT_CPU_FREQ_MHZ_240: n
      CONFIG_ESPTOOLPY_FLASHMODE_QIO: y
      CONFIG_ESPTOOLPY_FLASHFREQ_80M: y
      CONFIG_ESPTOOLPY_FLASHFREQ_120M: n
      CONFIG_SPIRAM_MODE_OCT: y
      CONFIG_IDF_EXPERIMENTAL_FEATURES: y
      CONFIG_SPIRAM_SPEED_80M: y
      CONFIG_SPIRAM_SPEED_120M: n
      CONFIG_SPIRAM_FETCH_INSTRUCTIONS: y
      CONFIG_SPIRAM_RODATA: y
      CONFIG_ESP32S3_DATA_CACHE_LINE_64B: y
      CONFIG_COMPILER_OPTIMIZATION_PERF: y

psram:
  mode: octal
  speed: 80MHz

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:

api:

ota:
  platform: esphome



# Ekspander IO CH422G (RESET/DISP dla LCD, RST dla touch)
i2c:
  id: bus_a
  sda: GPIO08 # TP_SDA (GT911) - wspólna magistrala
  scl: GPIO09 # TP_SCL (GT911)
  scan: true

ch422g:
  - id: ch422g_hub
    # address: 0x24   # często 0x24; jeśli skan I²C nie znajdzie, skomentuj tę linię


disp_pin:

output:
  - platform: gpio
    id: lcd_disp_enablep
      ch422g: ch422g_hub
      number: 2

light:
  - platform: monochromatic
    name: "Podświetlenie LCD"
    output: backlight_pwm
    id: backlight


# Ekran RGB 1024x600 (RPI_DPI_RGB)
display:
  - platform: rpi_dpi_rgb
    id: my_display
    update_interval: never
    auto_clear_enabled: false
    color_order: RGB
    

    # 1024x600 @ ~16 MHz (punkty startowe; w razie artefaktów skoryguj)
    pclk_frequency: 16MHz
    pclk_inverted: true

    dimensions:
      width: 1024
      height: 600

    # Piny synchronizacji i zegara (wg Waveshare Pinouts)
    hsync_pin:
      number: 46 # HSYNC
      ignore_strapping_warning: true
    vsync_pin:
      number: 3 # VSYNC
      ignore_strapping_warning: true
    de_pin:
      number: 5 # DE
    pclk_pin: 7 # PCLK

    # Reset i włączenie LCD przez CH422G
    reset_pin:
      ch422g: ch422g_hub
      number: 3 # EXIO3 -> LCD_RST (wg Pinouts)
      mode: OUTPUT
    enable_pin:
      ch422g: ch422g_hub
      number: 2 # EXIO2 -> DISP (Display Enable)
      mode: OUTPUT

    # Linie danych RGB (wg Pinouts: R3..R7, G2..G7, B3..B7)
    data_pins:
      red:
        - 1 # R3 (GPIO1)
        - 2 # R4 (GPIO2)
        - 42 # R5 (GPIO42)
        - 41 # R6 (GPIO41)
        - 40 # R7 (GPIO40)
      green:
        - 39 # G2 (GPIO39)
        - 0 # G3 (GPIO0)
        - 45 # G4 (GPIO45)
        - 48 # G5 (GPIO48)
        - 47 # G6 (GPIO47)
        - 21 # G7 (GPIO21)
      blue:
        - 14 # B3 (GPIO14)
        - 38 # B4 (GPIO38)
        - 18 # B5 (GPIO18)
        - 17 # B6 (GPIO17)
        - 10 # B7 (GPIO10)

    # Timingi startowe – dla 1024x600 często działają okolice tych wartości
    # Jeśli obraz jest przesunięty/drży, koryguj kolejno: hsync_* potem vsync_*, na końcu pclk.
    hsync_pulse_width: 20
    hsync_front_porch: 160
    hsync_back_porch: 160
    vsync_pulse_width: 3
    vsync_front_porch: 12
    vsync_back_porch: 23

# Panel dotykowy GT911 (I²C na GPIO8/9, IRQ na GPIO4, RST z CH422G EXIO1)
touchscreen:
  platform: gt911
  id: my_touch
  address: 0x5D # GT911 typowo 0x5D; jeśli skan pokaże 0x14/0x5D — dopasuj
  interrupt_pin: GPIO4 # TP_IRQ
  reset_pin:
    ch422g: ch422g_hub
    number: 1 # EXIO1 -> TP_RST (wg Pinouts)
    mode: OUTPUT
  on_touch:
    - lambda: |-
        ESP_LOGI("Touch", "Touch: x=%d y=%d", touch.x, touch.y);
  on_update:
    - lambda: |-
        for (auto t : touches) {
          if (t.state <= 2) {
            ESP_LOGI("Touch pts", "id=%d x=%d y=%d xr=%d yr=%d", t.id, t.x, t.y, t.x_raw, t.y_raw);
          }
        }
  on_release:
    then:
      - if:
          condition: lvgl.is_paused
          then:
            - lvgl.resume:
            - lvgl.widget.redraw:
